""" Adding langauge field to posts table 

Revision ID: 4ef32839f8ad
Revises: 8e1f32fc4281
Create Date: 2022-12-05 11:36:41.713660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef32839f8ad'
down_revision = '8e1f32fc4281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('langauge', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'langauge')
    # ### end Alembic commands ###
